### ISSUE TITLE
Feel free to use already done benchmarks :)

### ISSUE THREAD

**Issue by ducha-aiki** [dividiti/ck-caffe#3] opened 2016-09-02 15:50 UTC
https://github.com/ducha-aiki/caffenet-benchmark

**Comment by gfursin** [comment] 2016-09-07 19:32
Thanks for the note - really great project and very interesting results! I believe we should be able to integrate your parametrized models to our CK crowdtuning workflow to crowdsource its optimization. Just need to find time now ;) ...

By the way, at the moment we are focusing more on lower level optimizations as well as building infrastructure for collaborative and reproducible benchmarking and tuning (otherwise, it's really tricky to run experiments and process varying results across numerous machines with continuously changing software and hardware). After crowdsourcing compiler tuning, we now got lots of practical experience about how to solve above issues. In case of interest, here are a few of our articles with our long-term vision:
- http://bit.ly/ck-cnn
- http://arxiv.org/abs/1506.06256
- https://hal.inria.fr/hal-01054763

Will be happy to keep in touch!

**Comment by psyhtest** [comment] 2017-04-11 12:21
Since @mrgloom's request (issue #73) is a superset of @ducha-aiki's request (issue #3), I'm closing the latter for now.

**Closed as completed** 2017-04-11 12:22 UTC
Labels: question
